git add 	cors_exploit/.gitignore
git add 	cors_exploit/README
git add 	cors_exploit/amos.tf
git add 	cors_exploit/httpd.conf
git add 	cors_exploit/iam.tf
git add 	cors_exploit/local.tf
git add 	cors_exploit/networking.tf
git add 	cors_exploit/provider.tf
git add 	cors_exploit/sg.tf
git add 	cors_exploit/windows.tf
git add 	direct_connect/aws_network_10_Transit_Gateway.txt
git add 	direct_connect/aws_network_11_Hybrid_Networking_Basics.txt
git add 	direct_connect/aws_network_12_site_to_site_VPN.txt
git add 	direct_connect/aws_network_14_Direct_connect_first_pass.txt
git add 	direct_connect/aws_network_15_cloudwan.txt
git add 	direct_connect/aws_network_16_lattice.txt
git add 	direct_connect/aws_network_17_cloudfront.txt
git add 	direct_connect/aws_network_21_eks_networking.txt
git add 	direct_connect/aws_network_6_network_performance_and_optimization.txt
git add 	direct_connect/aws_network_8_VPC_private_connectivity_VPC_peering.txt
git add 	direct_connect/aws_network_first_course.txt
git add 	direct_connect/aws_networking_bgp.txt
git add 	direct_connect/aws_networking_dx.txt
git add 	eks/README
git add 	eks/eks.tf
git add 	eks/eks_canned_polices.tf
git add 	eks/iam.tf
git add 	eks/kms.tf
git add 	eks/kubernetes.sh
git add 	eks/networking.tf
git add 	eks/output.tf
git add 	eks/provider.tf
git add 	eks/route53.tf
git add 	eks/sg.tf
git add 	eks/subnet.tf
git add 	eks/temp/
git add 	eks/web-server-deployment.yaml
git add 	eks/web-server-service.yaml
git add 	global_accelerator/global_accelerator.tf
git add 	global_accelerator/networking.tf
git add 	global_accelerator/provider.tf
git add 	ipv6/igw.tf
git add 	ipv6/provider.tf
git add 	ipv6/subnet.tf
git add 	ipv6/vpc.tf
git add 	irtgp/.gitignore
git add 	irtgp/README
git add 	irtgp/af-south-1/
git add 	irtgp/ap-southeast-6/.gitignore
git add 	irtgp/ap-southeast-6/ec2.tf
git add 	irtgp/ap-southeast-6/eip.tf
git add 	irtgp/ap-southeast-6/igw.tf
git add 	irtgp/ap-southeast-6/local.tf
git add 	irtgp/ap-southeast-6/ngw.tf
git add 	irtgp/ap-southeast-6/output.tf
git add 	irtgp/ap-southeast-6/provider.tf
git add 	irtgp/ap-southeast-6/remote_state.tf
git add 	irtgp/ap-southeast-6/routing.tf
git add 	irtgp/ap-southeast-6/sg.tf
git add 	irtgp/ap-southeast-6/subnet.tf
git add 	irtgp/ap-southeast-6/tgw.tf
git add 	irtgp/ap-southeast-6/vpc.tf
git add 	irtgp/ashburn
git add 	irtgp/auckland
git add 	irtgp/capetown
git add 	irtgp/eu-west-2/ec2.tf
git add 	irtgp/eu-west-2/ec2.tf.old
git add 	irtgp/eu-west-2/eip.tf
git add 	irtgp/eu-west-2/igw.tf
git add 	irtgp/eu-west-2/local.tf
git add 	irtgp/eu-west-2/ngw.tf
git add 	irtgp/eu-west-2/output.tf
git add 	irtgp/eu-west-2/provider.tf
git add 	irtgp/eu-west-2/remote_state.tf
git add 	irtgp/eu-west-2/routing.tf
git add 	irtgp/eu-west-2/sg.tf
git add 	irtgp/eu-west-2/subnet.tf
git add 	irtgp/eu-west-2/tgw.tf
git add 	irtgp/eu-west-2/vpc.tf
git add 	irtgp/iam_common.tf
git add 	irtgp/irtgp/
git add 	irtgp/london
git add 	irtgp/provider.tf
git add 	irtgp/us-east-1/.gitignore
git add 	irtgp/us-east-1/ec2.tf
git add 	irtgp/us-east-1/eip.tf
git add 	irtgp/us-east-1/igw.tf
git add 	irtgp/us-east-1/local.tf
git add 	irtgp/us-east-1/ngw.tf
git add 	irtgp/us-east-1/output.tf
git add 	irtgp/us-east-1/provider.tf
git add 	irtgp/us-east-1/remote_state.tf
git add 	irtgp/us-east-1/routing.tf
git add 	irtgp/us-east-1/sg.tf
git add 	irtgp/us-east-1/subnet.tf
git add 	irtgp/us-east-1/tgw.tf
git add 	irtgp/us-east-1/vpc.tf
git add 	mcp/server-code/.venv/
git add 	temp.sh
git add 	vpc_watcher/.gitignore
git add 	vpc_watcher/event.tf
git add 	vpc_watcher/iam.tf
git add 	vpc_watcher/lambda.tf
git add 	vpc_watcher/lambda/
git add 	vpc_watcher/provider.tf
git add 	vpc_watcher/vpc/
git add 
