- name: Create region
  panos_region:
    provider: '{{ provider }}'
    name: '{{ item.name }}'   #String
  register: create_region
  until: create_region is not failed
  retries: 3
  with_items:
    - { name: 'AF'}
    - { name: 'AL'}
    - { name: 'DZ'}
    - { name: 'AD'}
    - { name: 'AO'}
    - { name: 'AQ'}
    - { name: 'AR'}
    - { name: 'AM'}
    - { name: 'AT'}
    - { name: 'AZ'}
    - { name: 'BH'}
    - { name: 'BD'}
    - { name: 'BY'}
    - { name: 'BE'}
    - { name: 'BJ'}
    - { name: 'BT'}
    - { name: 'BO'}
    - { name: 'BA'}
    - { name: 'BW'}
    - { name: 'BV'}
    - { name: 'BR'}
    - { name: 'BN'}
    - { name: 'BG'}
    - { name: 'BF'}
    - { name: 'BI'}
    - { name: 'KH'}
    - { name: 'CM'}
    - { name: 'CV'}
    - { name: 'CF'}
    - { name: 'TD'}
    - { name: 'CL'}
    - { name: 'CN'}
    - { name: 'CX'}
    - { name: 'CC'}
    - { name: 'CO'}
    - { name: 'KM'}
    - { name: 'CG'}
    - { name: 'CD'}
    - { name: 'CK'}
    - { name: 'HR'}
    - { name: 'CI'}
    - { name: 'CU'}
    - { name: 'CW'}
    - { name: 'CY'}
    - { name: 'CZ'}
    - { name: 'DK'}
    - { name: 'DJ'}
    - { name: 'EC'}
    - { name: 'EG'}
    - { name: 'GQ'}
    - { name: 'ER'}
    - { name: 'EE'}
    - { name: 'ET'}
    - { name: 'EU'}
    - { name: 'FK'}
    - { name: 'FO'}
    - { name: 'FJ'}
    - { name: 'FI'}
    - { name: 'FR'}
    - { name: 'GF'}
    - { name: 'PF'}
    - { name: 'GA'}
    - { name: 'GM'}
    - { name: 'GE'}
    - { name: 'DE'}
    - { name: 'GH'}
    - { name: 'GI'}
    - { name: 'GR'}
    - { name: 'GG'}
    - { name: 'GN'}
    - { name: 'GW'}
    - { name: 'GY'}
    - { name: 'VA'}
    - { name: 'HK'}
    - { name: 'HU'}
    - { name: 'IS'}
    - { name: 'IN'}
    - { name: 'ID'}
    - { name: 'IR'}
    - { name: 'IQ'}
    - { name: 'IE'}
    - { name: 'IM'}
    - { name: 'IL'}
    - { name: 'IT'}
    - { name: 'JP'}
    - { name: 'JE'}
    - { name: 'JO'}
    - { name: 'KZ'}
    - { name: 'KE'}
    - { name: 'KI'}
    - { name: 'KP'}
    - { name: 'KR'}
    - { name: 'KW'}
    - { name: 'KG'}
    - { name: 'AX'}
    - { name: 'LA'}
    - { name: 'LV'}
    - { name: 'LB'}
    - { name: 'LS'}
    - { name: 'LR'}
    - { name: 'LY'}
    - { name: 'LI'}
    - { name: 'LT'}
    - { name: 'LU'}
    - { name: 'MO'}
    - { name: 'MK'}
    - { name: 'MG'}
    - { name: 'MW'}
    - { name: 'MY'}
    - { name: 'MV'}
    - { name: 'ML'}
    - { name: 'MT'}
    - { name: 'MH'}
    - { name: 'MR'}
    - { name: 'MU'}
    - { name: 'YT'}
    - { name: 'FM'}
    - { name: 'MD'}
    - { name: 'MC'}
    - { name: 'MN'}
    - { name: 'ME'}
    - { name: 'MA'}
    - { name: 'MZ'}
    - { name: 'MM'}
    - { name: 'NA'}
    - { name: 'NR'}
    - { name: 'NP'}
    - { name: 'NL'}
    - { name: 'NC'}
    - { name: 'NE'}
    - { name: 'NG'}
    - { name: 'NU'}
    - { name: 'NF'}
    - { name: 'MP'}
    - { name: 'NO'}
    - { name: 'OM'}
    - { name: 'PK'}
    - { name: 'PW'}
    - { name: 'PS'}
    - { name: 'PG'}
    - { name: 'PY'}
    - { name: 'PE'}
    - { name: 'PH'}
    - { name: 'PN'}
    - { name: 'PL'}
    - { name: 'PT'}
    - { name: 'QA'}
    - { name: 'RO'}
    - { name: 'RE'}
    - { name: 'RU'}
    - { name: 'RW'}
    - { name: 'SH'}
    - { name: 'WS'}
    - { name: 'SM'}
    - { name: 'ST'}
    - { name: 'SA'}
    - { name: 'SN'}
    - { name: 'RS'}
    - { name: 'SC'}
    - { name: 'SL'}
    - { name: 'SG'}
    - { name: 'SX'}
    - { name: 'SK'}
    - { name: 'SI'}
    - { name: 'SB'}
    - { name: 'SO'}
    - { name: 'ZA'}
    - { name: 'GS'}
    - { name: 'SS'}
    - { name: 'ES'}
    - { name: 'LK'}
    - { name: 'SD'}
    - { name: 'SR'}
    - { name: 'SJ'}
    - { name: 'SZ'}
    - { name: 'SE'}
    - { name: 'CH'}
    - { name: 'SY'}
    - { name: 'TW'}
    - { name: 'TJ'}
    - { name: 'TZ'}
    - { name: 'TH'}
    - { name: 'TL'}
    - { name: 'TG'}
    - { name: 'TK'}
    - { name: 'TO'}
    - { name: 'TN'}
    - { name: 'TR'}
    - { name: 'TM'}
    - { name: 'TV'}
    - { name: 'UG'}
    - { name: 'UA'}
    - { name: 'AE'}
    - { name: 'GB'}
    - { name: 'UY'}
    - { name: 'UZ'}
    - { name: 'VU'}
    - { name: 'VE'}
    - { name: 'VN'}
    - { name: 'WF'}
    - { name: 'EH'}
    - { name: 'YE'}
    - { name: 'ZM'}
    - { name: 'ZW'}
