- name: Remove address object
  panos_address_object:
    provider: '{{ provider }}'
    name: '{{ item.name }}'
    state: absent
  with_items:
    - { name: '3awz34f.impervadns.net - 45.60.152.57'}
    - { name: 'k2wf7mp.impervadns.net - 45.60.152.57'}
    - { name: 'b9k6oqy.impervadns.net - 45.60.152.57'}
    - { name: 'ats749m.impervadns.net - 45.60.152.57'}
    - { name: 'zrwfvrh.impervadns.net - 45.60.152.57'}
    - { name: 'ut96vk4.impervadns.net - 45.60.152.57'}
    - { name: 'fzdahrh.impervadns.net - 45.60.152.57'}
    - { name: 'r7oiakh.impervadns.net - 45.60.152.57'}
    - { name: 'owk8zur.impervadns.net - 45.60.152.57'}
    - { name: '66pmmb5.impervadns.net - 45.60.152.57'}
    - { name: '4tn8rg2.impervadns.net - 45.60.152.57'}
    - { name: 'gvl66bl.impervadns.net - 45.60.152.57'}
    - { name: '4jhjcor.impervadns.net - 45.60.152.57'}
    - { name: 'tcxt7ks.impervadns.net - 45.60.152.57'}
    - { name: 'fxop67v.impervadns.net - 45.60.152.57'}

